print(sum([2,4,6,12]))
print(all([True,False,True]))
print(any([True,False,False]))
print("HEHEHE".lower())
print(" he he".lstrip())
print("ithu chinchu".endswith("chinchu"))
print("ifyoucandream".find("can"))
print("boobooboobbom".count("o"))
print("huhuhuhu".replace("u","e"))
print({"e": "erumbu","o": "oombu"}.values())
print("/".join(["google.com","torrent"]))
print("boom\nroom")
